### ISSUE TITLE
prevent from adding empty task

### ISSUE THREAD

**Issue by Naresh-chandanbatve** [web-contribution-DWOC/todo-web-app#2]
Now we can add empty tasks
but there should not be any empty tasks
prevent this behaviour

![Screenshot 2022-12-09 193452](https://user-images.githubusercontent.com/70953218/206719864-7354e16f-6fce-4411-8063-6fcd8eed6644.png)

**Comment by adrianmarinwork** [comment]
Hello, can I take care of this issue?

**Comment by Naresh-chandanbatve** [comment]
@adrianmarinwork 
Go for it.
